//
//  GridWindowAction.swift
//  Loop
//
//  Created by Codex on 2026-02-13.
//

import CoreGraphics

enum GridWindowAction {
    private static let autogeneratedActionName = "autogenerated_grid_action"

    static func createAction(from cells: Set<GridCell>, config: GridConfiguration, screen: CGRect) -> WindowAction {
        guard
            !cells.isEmpty,
            config.columns > 0,
            config.rows > 0,
            screen.width > 0,
            screen.height > 0
        else {
            return .init(.noSelection)
        }

        let rows = cells.map(\.row)
        let columns = cells.map(\.column)

        guard
            let minRow = rows.min(),
            let maxRow = rows.max(),
            let minColumn = columns.min(),
            let maxColumn = columns.max()
        else {
            return .init(.noSelection)
        }

        let widthPercent = (Double(maxColumn - minColumn + 1) / Double(config.columns)) * 100
        let heightPercent = (Double(maxRow - minRow + 1) / Double(config.rows)) * 100
        let xPercent = (Double(minColumn) / Double(config.columns)) * 100
        let yPercent = (Double(minRow) / Double(config.rows)) * 100

        return .init(
            .custom,
            keybind: [],
            name: autogeneratedActionName,
            unit: .percentage,
            width: widthPercent,
            height: heightPercent,
            xPoint: xPercent,
            yPoint: yPercent,
            positionMode: .coordinates,
            sizeMode: .custom
        )
    }
}
